### ISSUE TITLE
resource provider 만들기

### ISSUE THREAD

**Issue by yoonsung0711-1** [NamsooCho/WebServer_1#10]
## Implementing a Resource Provider

https://github.com/thuleqaid/rust-chardet
https://github.com/hsivonen/encoding_rs

* resource provider

    * automated decoder selection from byte stream with the help of chardet 

    * decode bytes into valid UTF-8 string

### procedures

* read bytes from a file into a bytes vector.
 
* detect charset of the file

* decode a stream of bytes into valid string

**Comment by yoonsung0711-1** [comment]
파일 처리기 앞단에 resource provider 만들어서
bytes stream으로부터 encoder를 탐지하고.. 탐지 결과에 따라 적절하게 decording된 string을 공급하도록 하고
이후에는 web server clien로부터 수신한 bytes를 파일처리하도록 바꿔 나가면 어떨까 싶습니다 ^^..

**Comment by NamsooCho** [comment]
향후 계획이 있다면 로드맵을 적당히 알려주세요

**Comment by yoonsung0711-1** [comment]
음.. 지금은 일단 파일처리기 관련해서
1. EUC-KR 완성형 한글 파일 읽어서 String 변환
2. tcp 네트워크 통신으로 byte stream 송수신 하기
3. 파일처리기 변형 (객체로 쪼개기 -> call back  -> pub-sub)
encoding, network, design pattern 이 세 가지를 연습해나가려고 합니다.

위의 세 가지가 어느 정도 만들어진 이후에는 
가능하다면 futures, tokio도 써보고 싶은데
이외에도 러스트를 공부하는 데 있어
효과적인 방법이나 방향을 알려주신다면 
참고하도록 하겠습니다. ^^..
