### ISSUE TITLE
file processor 만들기

### ISSUE THREAD

**Issue by yoonsung0711-1** [NamsooCho/WebServer_1#6]
## Implementing a File Processor 

https://github.com/crista/exercises-in-programming-style/blob/master/05-cookbook/tf-05.py

* Word Counter 

### procedures

* read text file encoded with utf-8

    * slicing off __BOM__ from loaded text 

* normalize characters using map() - 

    * drop non_alphabet chars

    * conversion chars to lower cased 

* split words and remove stop-words 

    * split __String__ into __Vec<&str>__ for iteration

    * filter stop words from original text

* counting words frequencies

    * save pairs of word with frequency pair into __HashMap__

* get sorted words frequencies by top 25

   *  sort __HashMap__ by value

**Comment by NamsooCho** [comment]
무엇 보다 먼저...
단어 카운터가 웹서버의 어느 부분에 쓰이는건지...
`stop words`라는 건 무엇을 말하는지...
sorting을 위해서는 hashmap 말고 BTreeMap같은것이 있습니다.

**Comment by yoonsung0711-1** [comment]
음.. 웹 서버의 자체의 기본 기능과는 무관하구요
http 서버나 tcp server에 붙여서 서비스 할 비즈니스 로직(데이터 처리) 중 하나라 가정했습니다. ^^..

file io, encoding, (추후 byte stream) 관련해서 
다양하게 실습해보기 좋은 주제라 생각해서 word counter를 선택하게 되었구
나중에 이 기능을 변경해서 map reduce로 코드를 바꿔나가면서 
자연스럽게 thread 쪽까지 연습이 되지 않을까 했습니다 ^^.. 

stop words는 접속사, 관사, 조사 같이 보조적으로 쓰이는 단어들을 의미하더라구요 
https://github.com/crista/exercises-in-programming-style/blob/master/stop_words.txt

만약에 이 이슈가 받아들여진다면 BTreeMap은 HashMap 구현을 마친 이후 변경하도록 하겠습니다 ^^ 

> 무엇 보다 먼저...
> 단어 카운터가 웹서버의 어느 부분에 쓰이는건지...
> `stop words`라는 건 무엇을 말하는지...
> sorting을 위해서는 hashmap 말고 BTreeMap같은것이 있습니다.

**Comment by NamsooCho** [comment]
현재 이 리포지터리 이름이 웹 서버이고, 서비스할 비즈니스 로직도 좋습니다.
다만 이 웹서버의 main에서 연동되어서 같이 묶이기만 하면 상관 없습니다.
BTreeMap은 hashmap과 비슷한데 sorting기능을 제공하는 것입니다.
굳이 hashmap으로 구현하고 나중에 BTreeMap으로 바꿀 필요는 없어 보입니다.

**Comment by yoonsung0711-1** [comment]
네.. ^^.. 아직은 러스트가 많이 익숙하지 않다보니
기존에 다른 언어로 공부했던 내용들을 변형해 보려구요
나중에 완성되면 메인에서 서비스와 url matching하도록 하겠습니다.
Assignee로 등록부탁드립니다

> 현재 이 리포지터리 이름이 웹 서버이고, 서비스할 비즈니스 로직도 좋습니다.
> 다만 이 웹서버의 main에서 연동되어서 같이 묶이기만 하면 상관 없습니다.
> BTreeMap은 hashmap과 비슷한데 sorting기능을 제공하는 것입니다.
> 굳이 hashmap으로 구현하고 나중에 BTreeMap으로 바꿀 필요는 없어 보입니다.
